name: Deploy CaféSerra to EC2

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cafeserra-onepage:latest .

      - name: Show image info
        run: docker images cafeserra-onepage

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "site/index.html"
          target: "/tmp/"
          strip_components: 1

      - name: Move file to nginx folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo cp /tmp/index.html /var/www/html/index.html
            sudo systemctl reload nginx
